build: &build
  docker:
    - image: rust:latest
      environment:
        BINARY: wifi-connect
        TARGET_OS: linux

  steps:
    - checkout

    - run: cargo build --release --target=$TARGET

    - run: cross-strip target/$TARGET/release/$BINARY

    - run: |
        VERSION=$CIRCLE_TAG
        if [ -z "$CIRCLE_TAG" ]; then VERSION="$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)"; fi
        echo "VERSION=$VERSION"
        echo "export VERSION=$VERSION" >> $BASH_ENV

    - run: |
        ARCHIVE_NAME="$BINARY-$VERSION-$TARGET_OS-$CIRCLE_JOB.tar.gz"
        echo "ARCHIVE_NAME=$ARCHIVE_NAME"
        echo "export ARCHIVE_NAME=$ARCHIVE_NAME" >> $BASH_ENV

    - run: |
        ARCHIVE_PATH="/tmp/dist/$ARCHIVE_NAME"
        echo "ARCHIVE_PATH=$ARCHIVE_PATH"
        echo "export ARCHIVE_PATH=$ARCHIVE_PATH" >> $BASH_ENV

    - run: mkdir -p pack /tmp/dist
    - run: mv target/$TARGET/release/$BINARY pack/$BINARY
    - run: cp -R ui/build pack/ui
    - run: tar -czvf $ARCHIVE_PATH -C pack .
    - run: rm -rdf pack

    - store_artifacts:
        path: /tmp/dist
        destination: /

version: 2

jobs:
  aarch64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.large
    <<: *build
    environment:
      TARGET: aarch64-unknown-linux-gnu

workflows:
  version: 2
  build:
    jobs:
      - aarch64:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
