version: 2

jobs:
  aarch64:
    docker:
      - image: cimg/rust:1.67.0
# Read up: https://kerkour.com/rust-cross-compilation, https://www.modio.se/cross-compiling-rust-binaries-to-armv7.html
    steps:
      - checkout
      - run: export CROSS_CONTAINER_IN_CONTAINER=true
      - run: cargo install cross --git https://github.com/cross-rs/cross

      - run: cross build --release --target=$TARGET

      - run: |
          VERSION=$CIRCLE_TAG
          if [ -z "$CIRCLE_TAG" ]; then VERSION="$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)"; fi
          echo "VERSION=$VERSION"
          echo "export VERSION=$VERSION" >> $BASH_ENV

      - run: |
          ARCHIVE_NAME="$BINARY-$VERSION-$TARGET_OS-$CIRCLE_JOB.tar.gz"
          echo "ARCHIVE_NAME=$ARCHIVE_NAME"
          echo "export ARCHIVE_NAME=$ARCHIVE_NAME" >> $BASH_ENV

      - run: |
          ARCHIVE_PATH="/tmp/dist/$ARCHIVE_NAME"
          echo "ARCHIVE_PATH=$ARCHIVE_PATH"
          echo "export ARCHIVE_PATH=$ARCHIVE_PATH" >> $BASH_ENV

      - run: mkdir -p pack /tmp/dist
      - run: mv target/$TARGET/release/$BINARY pack/$BINARY
      - run: cp -R ui/build pack/ui
      - run: tar -czvf $ARCHIVE_PATH -C pack .
      - run: rm -rdf pack

      - store_artifacts:
          path: /tmp/dist
          destination: /
    environment:
      TARGET: aarch64-unknown-linux-gnu

workflows:
  version: 2
  build:
    jobs:
      - aarch64:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
